# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec3e5ff8a18bc32d099b9158490ebb4156c828d8e33ed687b151946abdc0ded8fd79a38e933abc2de4595568f1f162a0b62c2ac1efd0406eaaa3b40a05fe278d

test:
  secret_key_base: affb0ec352c6ff3a0b9d2a35418ed03c466cc7194279a22bde94d5c32ee3ac2141646737c8dc45447c9a8a303a18b4b57ec6e967e40104414e97ffa4d24916b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
